macos_machine:
  - x86_64-apple-darwin13.4.0
  - arm64-apple-darwin20.0.0
cross_target_platform:
  - osx-64
  - osx-arm64
gfortran_version:
  - 15.1.0
  - 14.3.0
  - 13.4.0
zip_keys:
  - - cross_target_platform
    - macos_machine
# only for linux; osx is covered by c_stdlib_version from global pinning
MACOSX_DEPLOYMENT_TARGET:   # [not osx]
  - 10.9                    # [not osx]
