{% if gfortran_version is not defined %}
{% set gfortran_version = "15.1.0" %}
{% endif %}
{% set version = gfortran_version %}

{% set libgfortran_major_version = "5" %}

package:
  name: gfortran-split
  version: {{ version }}

build:
  number: 0
  skip: True  # [win]

outputs:
  - name: gfortran_{{ cross_target_platform }}
    script: build_gfortran.sh
    build:
      run_exports:
        strong:
          - libgfortran {{ libgfortran_major_version }}.*
          - libgfortran{{ libgfortran_major_version }} >={{ version }}
      ignore_run_exports_from:
        - gfortran_{{ target_platform }}
    requirements:
      build:
      host:
        - gfortran_impl_{{ cross_target_platform }} =={{ version }}
        - clang_{{ target_platform }}    # [osx]
        - gcc_{{ target_platform }}      # [linux]
      run:
        - clang
        - ld64_{{ cross_target_platform }}
        - cctools_{{ cross_target_platform }}
        - gfortran_impl_{{ cross_target_platform }} =={{ version }}
        - gfortran_impl_{{ target_platform }}
        - libgfortran-devel_{{ cross_target_platform }} =={{ version }}
        - libgfortran-devel_{{ target_platform }}         # [osx]
        - libgfortran {{ libgfortran_major_version }}.*               # [target_platform == cross_target_platform]
        - libgfortran{{ libgfortran_major_version }} >={{ version }}  # [target_platform == cross_target_platform]
        - clang_{{ cross_target_platform }}
    test:
      files:
        - hello.f90
        - maths.f90
      commands:
        - echo {{ MACOSX_DEPLOYMENT_TARGET }}
        - {{ macos_machine }}-gfortran --help
        - test "$(readlink $PREFIX/lib/gcc/{{ macos_machine }}/{{ version }}/clang)" = "../../../../bin/clang"

  - name: gfortran
    script: install_symlink.sh
    build:
      skip: True  # [cross_target_platform != target_platform]
      skip: True  # [win]
    requirements:
      host:
        - gfortran_{{ cross_target_platform }} =={{ version }}
      run:
        - gfortran_{{ cross_target_platform }} =={{ version }}
        - ld64
        - cctools
    test:
      commands:
        - echo {{ MACOSX_DEPLOYMENT_TARGET }}
        - gfortran --help

about:
  home: http://gcc.gnu.org/
  license: GPL-3.0-or-later WITH GCC-exception-3.1
  license_file: COPYING3
  summary: Fortran compiler from the GNU Compiler Collection

extra:
  recipe-maintainers:
    - beckermr
    - isuruf
    - erykoff
