{% set version = "7.3.0" %}
{% set libgfortran_version = "4.0.0" %}
{% set max_libgfortran_version = "5.0.0.a0" %}

package:
  name: gfortran_osx-64
  version: {{ version }}

build:
  number: 6
  skip: True  # [not osx]
  run_exports:
    strong:
      - libgfortran >={{ libgfortran_version }},<{{ max_libgfortran_version }}

requirements:
  host:
    - clang
    - ld64
    - cctools
    - gfortran_impl_osx-64 =={{ version }}
    - libgfortran >={{ libgfortran_version }},<{{ max_libgfortran_version }}
  run:
    - clang
    - ld64
    - cctools
    - gfortran_impl_osx-64 =={{ version }}
    - libgfortran >={{ libgfortran_version }},<{{ max_libgfortran_version }}

test:
  files:
    - hello.f90
    - maths.f90
  commands:
    - gfortran --help
    - test "$(readlink $PREFIX/lib/gcc/{{ macos_machine }}/{{ version }}/clang)" = "../../../../bin/clang"

about:
  home: http://gcc.gnu.org/
  license: GPL 3 (with GCC Runtime Library Exception 3.1)
  license_family: GPL
  license_file: COPYING3
  summary: Fortran compiler from the GNU Compiler Collection

extra:
  recipe-maintainers:
    - beckermr
